-- ==========================================
-- 🚀 GENZ IGNITE: MASTER DATABASE SETUP SCRIPT
-- ==========================================
-- 
-- !⚠️  DEPRECATED — RLS section (บรรทัด 76-129) มี policies อันตราย!
--    กำลังสร้าง INSERT/UPDATE/DELETE USING (true) = เปิดให้ทุกคนเขียน DB
--    ✅ ให้ใช้ db/04_admin_security_fix.sql แทน สำหรับ RLS policies
--
-- ส่วน CREATE TABLE ด้านบนปลอดภัย (IF NOT EXISTS) ใช้เป็น schema reference ได้
-- แต่ถ้าต้องการรันทั้งหมด → รัน 04_admin_security_fix.sql ทีหลังเพื่อ override policies
--
-- ==========================================

-- 1. สร้างตาราง Announcements (ประชาสัมพันธ์)
CREATE TABLE IF NOT EXISTS announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  category text NOT NULL CHECK (category IN ('ข่าวด่วน', 'กิจกรรม', 'ประกาศทั่วไป', 'ผลงานสภา')),
  image_url text,
  is_pinned boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- 2. สร้างตาราง Policies (นโยบาย)
CREATE TABLE IF NOT EXISTS policies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  category text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'in_progress', 'completed')),
  progress int DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  description text,
  image_url text,
  votes int DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now()
);

-- 3. สร้างตาราง Members (ทีมงาน)
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  nickname TEXT NOT NULL,
  role TEXT NOT NULL,
  quote TEXT,
  instagram TEXT,
  image_url TEXT,
  "order" INTEGER DEFAULT 0
);

-- 4. สร้างตาราง Complaints (ร้องเรียน)
CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  topic TEXT NOT NULL,
  message TEXT NOT NULL,
  category TEXT DEFAULT 'ทั่วไป',
  contact TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
  track_id uuid DEFAULT gen_random_uuid(),
  admin_reply text,
  resolved_at timestamp with time zone
);

-- 5. สร้างตาราง Polls (โพล)
CREATE TABLE IF NOT EXISTS polls (
  id SERIAL PRIMARY KEY,
  option_name TEXT NOT NULL,
  votes INTEGER DEFAULT 0
);

-- ใส่ข้อมูล Polls เริ่มต้นหากยังไม่มีรหัส 1
INSERT INTO polls (option_name, votes) 
SELECT 'วิชาการ/การเรียน', 12 WHERE NOT EXISTS (SELECT 1 FROM polls WHERE id = 1);
INSERT INTO polls (option_name, votes) 
SELECT 'สถานที่/สิ่งอำนวยความสะดวก', 25 WHERE NOT EXISTS (SELECT 1 FROM polls WHERE id = 2);
INSERT INTO polls (option_name, votes) 
SELECT 'กิจกรรม/กีฬา', 18 WHERE NOT EXISTS (SELECT 1 FROM polls WHERE id = 3);
INSERT INTO polls (option_name, votes) 
SELECT 'ความโปร่งใส/งบประมาณ', 40 WHERE NOT EXISTS (SELECT 1 FROM polls WHERE id = 4);


-- ==========================================
-- 🔓 เปิดใช้งาน Row Level Security (RLS) และให้สิทธิ์แอดมินเขียน/แก้ไข
-- ==========================================

-- Announcements
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public announcements are viewable by everyone" ON announcements;
CREATE POLICY "Public announcements are viewable by everyone" ON announcements FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert for announcements" ON announcements;
CREATE POLICY "Enable insert for announcements" ON announcements FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for announcements" ON announcements;
CREATE POLICY "Enable update for announcements" ON announcements FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable delete for announcements" ON announcements;
CREATE POLICY "Enable delete for announcements" ON announcements FOR DELETE USING (true);

-- Policies
ALTER TABLE policies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public policies are viewable by everyone" ON policies;
CREATE POLICY "Public policies are viewable by everyone" ON policies FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert for policies" ON policies;
CREATE POLICY "Enable insert for policies" ON policies FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for policies" ON policies;
CREATE POLICY "Enable update for policies" ON policies FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable delete for policies" ON policies;
CREATE POLICY "Enable delete for policies" ON policies FOR DELETE USING (true);

-- Members
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON members;
CREATE POLICY "Enable read access for all users" ON members FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert for members" ON members;
CREATE POLICY "Enable insert for members" ON members FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for members" ON members;
CREATE POLICY "Enable update for members" ON members FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable delete for members" ON members;
CREATE POLICY "Enable delete for members" ON members FOR DELETE USING (true);

-- Complaints
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON complaints;
CREATE POLICY "Enable read access for all users" ON complaints FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert for complaints" ON complaints;
CREATE POLICY "Enable insert for complaints" ON complaints FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Enable update for complaints" ON complaints;
CREATE POLICY "Enable update for complaints" ON complaints FOR UPDATE USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Enable delete for complaints" ON complaints;
CREATE POLICY "Enable delete for complaints" ON complaints FOR DELETE USING (true);

-- Polls
ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public polls are viewable by everyone" ON polls;
CREATE POLICY "Public polls are viewable by everyone" ON polls FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public can vote" ON polls;
CREATE POLICY "Public can vote" ON polls FOR UPDATE USING (true) WITH CHECK (true);
