-- ⚠️ [DEPRECATED] — ห้ามใช้ไฟล์นี้เด็ดขาด!
-- 
-- ไฟล์นี้มี RLS policies ที่อันตราย: USING (true) = ใครก็ INSERT/UPDATE/DELETE ได้
-- 
-- ✅ ให้ใช้ db/04_admin_security_fix.sql แทน
--    ซึ่งใช้ role-based check ผ่าน public.is_admin() function
--    และรองรับ multi-admin
--
-- คำเตือน: ถ้ารันไฟล์นี้ จะเปิดช่องให้บุคคลทั่วไปเขียนข้อมูลลง database ได้
