-- Create members table
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  nickname TEXT NOT NULL,
  role TEXT NOT NULL,
  quote TEXT,
  instagram TEXT,
  image_url TEXT,
  "order" INTEGER DEFAULT 0
);

-- RLS Policies
ALTER TABLE members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON members
  FOR SELECT USING (true);
